import type { DeviceId, DeviceSpec } from './roleplayTypes';

export const VIRTUAL_EQUIPMENT_CATALOG: Record<DeviceId, DeviceSpec> = {
  CAMERA_BULLET: {
    id: 'CAMERA_BULLET',
    nameTh: 'กล้องวงจรปิด IP ทรงกระบอก (IP Bullet Camera)',
    nameEn: 'IP Bullet Camera 2MP / 4mm PoE',
    category: 'CAMERA',
    powerType: 'POE',
    powerWatts: 7.5,
    dimensions: [0.12, 0.12, 0.28],
    leds: ['POWER', 'LINK', 'ONLINE', 'IR_MODE'],
    descriptionTh: 'กล้องกระบอกพร้อมขายึดปรับมุม เลนส์ 4mm พร้อม IR LED ส่องสว่างกลางคืน รองรับ PoE 802.3af และมีพอร์ตสำรอง DC 12V',
    ports: [
      {
        id: 'CAM_BULLET_PORT_RJ45',
        name: 'LAN / PoE (RJ45)',
        portType: 'RJ45_POE',
        powerRequiredWatts: 7.5,
      },
      {
        id: 'CAM_BULLET_PORT_DC12V',
        name: 'DC 12V IN',
        portType: 'DC_12V',
        powerRequiredWatts: 7.5,
      },
    ],
  },
  CAMERA_DOME: {
    id: 'CAMERA_DOME',
    nameTh: 'กล้องวงจรปิด IP ทรงโดม (IP Dome Camera)',
    nameEn: 'IP Dome Camera 2MP / 2.8mm PoE (IK10)',
    category: 'CAMERA',
    powerType: 'POE',
    powerWatts: 6.0,
    dimensions: [0.14, 0.1, 0.14],
    leds: ['POWER', 'LINK', 'ONLINE'],
    descriptionTh: 'กล้องโดมติดฝ้าเพดาน มุมกว้าง เลนส์ 2.8mm ทนแรงกระแทก IK10 มาตรฐาน IP66 รองรับไฟผ่านสาย LAN (PoE)',
    ports: [
      {
        id: 'CAM_DOME_PORT_RJ45',
        name: 'LAN / PoE (RJ45)',
        portType: 'RJ45_POE',
        powerRequiredWatts: 6.0,
      },
      {
        id: 'CAM_DOME_PORT_DC12V',
        name: 'DC 12V IN',
        portType: 'DC_12V',
        powerRequiredWatts: 6.0,
      },
    ],
  },
  POE_SWITCH_8P: {
    id: 'POE_SWITCH_8P',
    nameTh: 'สวิตช์ PoE ขนาด 8 พอร์ต (8-Port PoE Switch)',
    nameEn: '8-Port Fast Ethernet PoE Switch + 2 Uplink (65W Budget)',
    category: 'NETWORK',
    powerType: 'AC',
    powerWatts: 15.0,
    dimensions: [0.28, 0.05, 0.18],
    leds: ['POWER', 'POE_MAX', 'PORT_1_LINK', 'PORT_2_LINK', 'PORT_3_LINK', 'PORT_4_LINK'],
    descriptionTh: 'สวิตช์จ่ายไฟ PoE พอร์ต 1–8 งบกำลังไฟรวม 65W และมีพอร์ต Uplink 2 พอร์ต (ไม่จ่ายไฟ PoE) สำหรับต่อ NVR และ Router',
    ports: [
      { id: 'POE_SW_P1', name: 'Port 1 (PoE 802.3af)', portType: 'RJ45_POE', isPoECapable: true, poePowerProvidedWatts: 15.4 },
      { id: 'POE_SW_P2', name: 'Port 2 (PoE 802.3af)', portType: 'RJ45_POE', isPoECapable: true, poePowerProvidedWatts: 15.4 },
      { id: 'POE_SW_P3', name: 'Port 3 (PoE 802.3af)', portType: 'RJ45_POE', isPoECapable: true, poePowerProvidedWatts: 15.4 },
      { id: 'POE_SW_P4', name: 'Port 4 (PoE 802.3af)', portType: 'RJ45_POE', isPoECapable: true, poePowerProvidedWatts: 15.4 },
      { id: 'POE_SW_P5', name: 'Port 5 (PoE 802.3af)', portType: 'RJ45_POE', isPoECapable: true, poePowerProvidedWatts: 15.4 },
      { id: 'POE_SW_P6', name: 'Port 6 (PoE 802.3af)', portType: 'RJ45_POE', isPoECapable: true, poePowerProvidedWatts: 15.4 },
      { id: 'POE_SW_P7', name: 'Port 7 (PoE 802.3af)', portType: 'RJ45_POE', isPoECapable: true, poePowerProvidedWatts: 15.4 },
      { id: 'POE_SW_P8', name: 'Port 8 (PoE 802.3af)', portType: 'RJ45_POE', isPoECapable: true, poePowerProvidedWatts: 15.4 },
      { id: 'POE_SW_UPLINK1', name: 'Uplink 1 (Non-PoE LAN)', portType: 'RJ45_LAN', isPoECapable: false },
      { id: 'POE_SW_UPLINK2', name: 'Uplink 2 (Non-PoE LAN)', portType: 'RJ45_LAN', isPoECapable: false },
    ],
  },
  NVR_8CH: {
    id: 'NVR_8CH',
    nameTh: 'เครื่องบันทึกภาพกล้องเครือข่าย (8-Channel NVR)',
    nameEn: '8-Channel Network Video Recorder (1x SATA HDD)',
    category: 'RECORDER',
    powerType: 'AC',
    powerWatts: 20.0,
    dimensions: [0.38, 0.06, 0.3],
    leds: ['POWER', 'HDD_STATUS', 'NET_LINK'],
    descriptionTh: 'เครื่อง NVR รับสัญญาณ Video Stream ดิจิทัลจากกล้อง IP ผ่านเครือข่าย ทำการบันทึกภาพลงฮาร์ดดิสก์ และส่งภาพสดออกจอ Monitor',
    ports: [
      { id: 'NVR_PORT_LAN', name: 'LAN (RJ45 Network)', portType: 'RJ45_LAN' },
      { id: 'NVR_PORT_HDMI_OUT', name: 'HDMI OUT (Display)', portType: 'HDMI_OUT' },
      { id: 'NVR_PORT_POWER', name: 'AC 220V Power IN', portType: 'DC_12V' },
    ],
  },
  ROUTER: {
    id: 'ROUTER',
    nameTh: 'เราเตอร์เครือข่าย (Network Gateway Router)',
    nameEn: 'Gigabit Broadband Router 1 WAN + 4 LAN',
    category: 'NETWORK',
    powerType: 'DC12V',
    powerWatts: 10.0,
    dimensions: [0.22, 0.04, 0.16],
    leds: ['POWER', 'WAN_INTERNET', 'LAN_ACTIVITY'],
    descriptionTh: 'อุปกรณ์เชื่อมต่อระหว่างเครือข่ายภายในร้าน (LAN) ออกสู่อินเทอร์เน็ต (WAN) สำหรับดูภาพผ่านมือถือ ไม่จำเป็นสำหรับการดูภาพสดในวง LAN เดียวกัน',
    ports: [
      { id: 'ROUTER_PORT_WAN', name: 'WAN (Internet Uplink)', portType: 'RJ45_LAN' },
      { id: 'ROUTER_PORT_LAN1', name: 'LAN 1', portType: 'RJ45_LAN' },
      { id: 'ROUTER_PORT_LAN2', name: 'LAN 2', portType: 'RJ45_LAN' },
    ],
  },
  CLIENT_PC: {
    id: 'CLIENT_PC',
    nameTh: 'เครื่องคอมพิวเตอร์ลูกข่าย (Client PC)',
    nameEn: 'Security Monitoring Client Workstation',
    category: 'CONTROL',
    powerType: 'AC',
    powerWatts: 120.0,
    dimensions: [0.18, 0.4, 0.42],
    leds: ['POWER', 'LAN_ACTIVITY'],
    descriptionTh: 'คอมพิวเตอร์ติดตั้งซอฟต์แวร์ VMS / Client ใช้ดูภาพสดจากกล้อง ค้นหาภาพย้อนหลัง และตั้งค่าระบบกล้องวงจรปิด',
    ports: [
      { id: 'CLIENT_PC_PORT_LAN', name: 'Ethernet LAN (RJ45)', portType: 'RJ45_LAN' },
      { id: 'CLIENT_PC_PORT_HDMI_OUT', name: 'HDMI OUT', portType: 'HDMI_OUT' },
    ],
  },
  MONITOR: {
    id: 'MONITOR',
    nameTh: 'จอภาพสำหรับกล้องวงจรปิด (24" CCTV Monitor)',
    nameEn: '24-Inch Full HD Surveillance Display',
    category: 'CONTROL',
    powerType: 'AC',
    powerWatts: 25.0,
    dimensions: [0.55, 0.36, 0.08],
    leds: ['POWER', 'HDMI_SIGNAL'],
    descriptionTh: 'จอแสดงผลความละเอียด Full HD แสดงผลภาพสดจาก NVR หรือ Client PC โดยจอทำหน้าที่แสดงผลอย่างเดียว ไม่ได้บันทึกภาพ',
    ports: [
      { id: 'MONITOR_PORT_HDMI_IN', name: 'HDMI IN', portType: 'HDMI_IN' },
      { id: 'MONITOR_PORT_POWER', name: 'AC Power IN', portType: 'DC_12V' },
    ],
  },
  ANALOG_CAMERA: {
    id: 'ANALOG_CAMERA',
    nameTh: 'กล้องวงจรปิดแบบอนาล็อก (Analog CCTV Camera)',
    nameEn: 'Analog HD Camera (BNC Coaxial + DC 12V)',
    category: 'ANALOG',
    powerType: 'DC12V',
    powerWatts: 5.0,
    dimensions: [0.1, 0.1, 0.2],
    leds: ['POWER'],
    descriptionTh: 'กล้องอนาล็อกส่งสัญญาณภาพผ่านสาย Coaxial (RG6) เข้าหัว BNC ต้องเดินสายไฟแยก และต้องต่อเข้า DVR เพื่อแปลงสัญญาณ',
    ports: [
      { id: 'ANALOG_CAM_BNC', name: 'Video Out (BNC)', portType: 'BNC' },
      { id: 'ANALOG_CAM_DC', name: 'DC 12V IN', portType: 'DC_12V' },
    ],
  },
  DVR: {
    id: 'DVR',
    nameTh: 'เครื่องบันทึกภาพอนาล็อก (Digital Video Recorder)',
    nameEn: 'Analog DVR (BNC Inputs + Video Encoder)',
    category: 'ANALOG',
    powerType: 'AC',
    powerWatts: 25.0,
    dimensions: [0.35, 0.06, 0.28],
    leds: ['POWER', 'HDD'],
    descriptionTh: 'เครื่อง DVR รับสัญญาณไฟฟ้าอนาล็อกผ่านสาย Coaxial แล้วแปลงเป็นไฟล์ดิจิทัลภายในเครื่องก่อนบันทึก',
    ports: [
      { id: 'DVR_BNC_IN', name: 'BNC CH1 IN', portType: 'BNC' },
      { id: 'DVR_HDMI_OUT', name: 'HDMI OUT', portType: 'HDMI_OUT' },
    ],
  },
};
